import * as github from '@actions/github';

// ADR-009: AIによるハルシネーション・フィッシング対策のための免責事項と隠しマーカー
const SIGNATURE = `
---
*🤖 This comment was generated by AI-Driven ADR Enforcer.*
*⚠️ **Disclaimer**: The reasoning and code suggestions above are AI-generated. They may contain hallucinations, including fake URLs or incorrect package names. Please verify all information manually before executing code or clicking links.*
<!-- ai-adr-enforcer-signature -->`;

/**
 * ADR-009: AIが生成したテキスト内のマークダウンリンクや画像をサニタイズ（エスケープ）します。
 * 悪意あるURL（フィッシングやSlopsquatting）への誘導を防ぐための防衛的処理です。
 * 
 * @param text LLMが生成した生のテキスト
 * @returns リンクが無効化されたテキスト
 */
export function sanitizeAiResponse(text: string): string {
  if (!text) return text;
  
  // Match & Skip パターン:
  // 1. code: バッククォートで囲まれた部分（無視する）
  // 2. img: ![alt](url)
  // 3. link: [text](url)
  // 4. rawUrl: むき出しのURL (http...)
  const regex = /(`{1,3}[\s\S]*?`{1,3})|!\[([^\]]*)\]\(([^)]+)\)|\[([^\]]+)\]\(([^)]+)\)|(https?:\/\/[^\s`()]+[a-zA-Z0-9/])/g;

  return text.replace(regex, (match, code, imgAlt, imgUrl, linkText, linkUrl, rawUrl) => {
    if (code) return match; // コードブロック内は安全とみなしそのまま
    if (imgUrl) return `\`[IMAGE: ${imgAlt}](${imgUrl})\``;
    if (linkUrl) return `\`[LINK: ${linkText}](${linkUrl})\``;
    if (rawUrl) return `\`${rawUrl}\``;
    return match;
  });
}

/**
 * Diffのノイズとなる自動生成ファイルやバイナリファイルのチャンクを除外します。
 * 
 * @param diff 生のPR Diff文字列
 * @returns フィルタリングされたDiff文字列
 */
export function filterDiffNoise(diff: string): string {
  // 除外対象のファイル拡張子またはファイル名のパターン
  const excludePatterns = [
    'package-lock\\.json',
    'yarn\\.lock',
    'pnpm-lock\\.yaml',
    '\\.svg$',
    '\\.png$',
    '\\.jpg$',
    '\\.map$',
  ];
  
  const excludeRegex = new RegExp(`diff --git a/.* b/.*(${excludePatterns.join('|')})`, 'i');
  
  // diffの各ファイルごとのチャンクを分割 ('diff --git' で始まる)
  const chunks = diff.split(/(?=^diff --git )/m);
  
  // パターンにマッチしないチャンクだけを残す
  const filteredChunks = chunks.filter(chunk => {
    // 最初の行をチェックして除外パターンに一致するか確認
    const firstLine = chunk.split('\n')[0] || '';
    return !excludeRegex.test(firstLine);
  });
  
  return filteredChunks.join('');
}

/**
 * GitHub API (Octokit) を使用して、指定された Pull Request の Diff (差分) を取得します。
 * 
 * @param token GitHub Personal Access Token (または GITHUB_TOKEN)
 * @param prNumber Diffを取得するPull Requestの番号
 * @returns PRのDiffを表す文字列
 */
export async function getPrDiff(token: string, prNumber: number): Promise<string> {
  try {
    const octokit = github.getOctokit(token);
    
    // context.repo には owner と repo が含まれている
    const { owner, repo } = github.context.repo;

    // mediaType.format に 'diff' を指定することで、JSONではなくDiffの生テキストを取得できる
    const response = await octokit.rest.pulls.get({
      owner,
      repo,
      pull_number: prNumber,
      mediaType: {
        format: 'diff',
      },
      request: {
        // ADR-003: タイムアウト設定 (30,000ms)
        signal: AbortSignal.timeout(30000),
      },
    });

    // response.data は Diff 形式の文字列として返ってくる
    return response.data as unknown as string;
  } catch (error) {
    if (error instanceof Error) {
      throw new Error(`Failed to fetch PR diff: ${error.message}`);
    }
    throw new Error('Failed to fetch PR diff: Unknown error');
  }
}

/**
 * Pull Request にコメントを投稿します。
 * スパム防止のため、以前にこのアクションが投稿したコメントが存在する場合は新規投稿ではなく更新（上書き）します。
 * 
 * @param token GitHub Token
 * @param prNumber 対象のPull Request番号
 * @param body コメントの本文（監査結果など）
 */
export async function postOrUpdateComment(token: string, prNumber: number, body: string): Promise<void> {
  const octokit = github.getOctokit(token);
  const { owner, repo } = github.context.repo;

  // コメントの末尾に署名を追加
  const commentBody = `${body}\n\n${SIGNATURE}`;

  try {
    // 既存のコメント一覧を取得
    const { data: comments } = await octokit.rest.issues.listComments({
      owner,
      repo,
      issue_number: prNumber,
    });

    // 署名を持つ既存のコメントを探す
    const existingComment = comments.find((comment) => comment.body?.includes('<!-- ai-adr-enforcer-signature -->'));

    if (existingComment) {
      // 既存のコメントがあれば更新する
      await octokit.rest.issues.updateComment({
        owner,
        repo,
        comment_id: existingComment.id,
        body: commentBody,
      });
    } else {
      // なければ新規作成する
      await octokit.rest.issues.createComment({
        owner,
        repo,
        issue_number: prNumber,
        body: commentBody,
      });
    }
  } catch (error) {
    if (error instanceof Error) {
      throw new Error(`Failed to post or update comment: ${error.message}`);
    }
    throw new Error('Failed to post or update comment: Unknown error');
  }
}

/**
 * PRに人間からの CHANGES_REQUESTED レビューが1つでも存在するか確認します。
 * 
 * @param token GitHub Token
 * @param prNumber 対象のPull Request番号
 * @returns 人間からの拒否レビューがある場合は true、なければ false
 */
export async function hasChangesRequestedFromHumans(token: string, prNumber: number): Promise<boolean> {
  try {
    const octokit = github.getOctokit(token);
    const { owner, repo } = github.context.repo;

    const { data: reviews } = await octokit.rest.pulls.listReviews({
      owner,
      repo,
      pull_number: prNumber,
    });

    // state === 'CHANGES_REQUESTED' かつ user.type === 'User'（人間）のレビューが存在するかチェック
    return reviews.some((review) => review.state === 'CHANGES_REQUESTED' && review.user?.type === 'User');
  } catch (error) {
    if (error instanceof Error) {
      throw new Error(`Failed to check human reviews: ${error.message}`);
    }
    throw new Error('Failed to check human reviews: Unknown error');
  }
}

/**
 * 対象の PR に対して自動承認（APPROVED）のレビューを安全に投稿します。
 * 
 * @param token GitHub Token
 * @param prNumber 対象のPull Request番号
 */
export async function submitAutoApproveReview(token: string, prNumber: number): Promise<void> {
  try {
    const octokit = github.getOctokit(token);
    const { owner, repo } = github.context.repo;

    await octokit.rest.pulls.createReview({
      owner,
      repo,
      pull_number: prNumber,
      event: 'APPROVE',
      body: '🤖 **AI-Driven ADR Enforcer**: Auto-approved as the changes are highly safe, low risk, and comply fully with all project ADR constraints.',
    });
  } catch (error) {
    if (error instanceof Error) {
      throw new Error(`Failed to submit auto approve review: ${error.message}`);
    }
    throw new Error('Failed to submit auto approve review: Unknown error');
  }
}

/**
 * PRで変更されたすべてのファイル名の一覧を取得します。
 * API Rate Limitを保護する防衛境界ルールに基づき、最大500ファイルまでに制限します。
 * 
 * @param token GitHub Token
 * @param prNumber 対象 of Pull Request番号
 * @returns 変更ファイル名の配列
 */
export async function getPrChangedFilesList(token: string, prNumber: number): Promise<string[]> {
  try {
    const octokit = github.getOctokit(token);
    const { owner, repo } = github.context.repo;

    const files: string[] = [];
    const maxFiles = 500;

    // pagination を用いて全ファイルを漏れなくスキャンする
    await octokit.paginate(
      octokit.rest.pulls.listFiles,
      {
        owner,
        repo,
        pull_number: prNumber,
        per_page: 100,
      },
      (response, done) => {
        const pageFiles = response.data.map((file) => file.filename);
        files.push(...pageFiles);

        // 防衛境界：500ファイル制限チェック
        if (files.length > maxFiles) {
          done(); // ページネーションをこれ以上進めない
        }
        return response.data;
      }
    );

    if (files.length > maxFiles) {
      throw new Error(`PR exceeds maximum allowed files limit (${maxFiles}).`);
    }

    return files;
  } catch (error) {
    if (error instanceof Error) {
      throw new Error(`Failed to fetch PR changed files: ${error.message}`);
    }
    throw new Error('Failed to fetch PR changed files: Unknown error');
  }
}

/**
 * PRに未解決のコメント（スレッド）が1つでも存在するか確認します。
 * 
 * @param token GitHub Token
 * @param prNumber 対象のPull Request番号
 * @returns 未解決のコメントスレッドがある場合は true、なければ false
 */
export async function hasUnresolvedComments(token: string, prNumber: number): Promise<boolean> {
  try {
    const octokit = github.getOctokit(token);
    const { owner, repo } = github.context.repo;

    const { data: comments } = await octokit.rest.pulls.listReviewComments({
      owner,
      repo,
      pull_number: prNumber,
    });

    // 各コメントに `resolved` プロパティがあり、それが `false` のものが存在するかチェック
    return comments.some((comment: any) => comment.resolved === false);
  } catch (error) {
    if (error instanceof Error) {
      throw new Error(`Failed to check unresolved comments: ${error.message}`);
    }
    throw new Error('Failed to check unresolved comments: Unknown error');
  }
}

/**
 * PRに投稿された人間（PR作成者以外の第三者）の全体コメント（タイムラインコメント）一覧を取得します。
 * Copilot等のBotの行コメントや、PR作成者自身のコメントは完全に無視されます。
 * 
 * @param token GitHub Token
 * @param prNumber 対象のPull Request番号
 * @param prAuthor PR作成者のユーザー名
 * @returns 人間の全体コメント本文の配列
 */
export async function getHumanGeneralComments(token: string, prNumber: number, prAuthor: string): Promise<string[]> {
  try {
    const octokit = github.getOctokit(token);
    const { owner, repo } = github.context.repo;

    const { data: comments } = await octokit.rest.issues.listComments({
      owner,
      repo,
      issue_number: prNumber,
    });

    return comments
      .filter((comment) => {
        const isHuman = comment.user?.type === 'User';
        const isNotPrAuthor = comment.user?.login !== prAuthor;
        const isNotActionComment = !comment.body?.includes('<!-- ai-adr-enforcer-signature -->');
        return isHuman && isNotPrAuthor && isNotActionComment;
      })
      .map((comment) => comment.body || '')
      .filter((body) => body.trim() !== '');
  } catch (error) {
    if (error instanceof Error) {
      throw new Error(`Failed to fetch human general comments: ${error.message}`);
    }
    throw new Error('Failed to fetch human general comments: Unknown error');
  }
}
